### ISSUE TITLE
New component is created, but template does not contain html

### ISSUE THREAD

**Issue by abdurrehman1998** [bilelmsekni/componizer#14]
I tried to refactor html block of a template into separate component, new component is created but it does not contain that html block

**Comment by maykon-oliveira** [comment]
Hi @abdurrehman1998,

I think you are facing that problem too [#7](https://github.com/bilelmsekni/componizer/issues/7#issuecomment-717508304), right?

**Comment by bilelmsekni** [comment]
@abdurrehman1998 can you update your extension and schematics to version 0.0.4 and let us know if the problem persists please ?

**Comment by bilelmsekni** [comment]
Fixed
