### ISSUE TITLE
Suffers when dealing with a path that has a space

### ISSUE THREAD

**Issue by UserNobody14** [bilelmsekni/componizer#17]
If one opens up a project in a folder/path in which one of the names has a space (for example C:/Whatever/My Code/angular-project/src/pasta/pasta-component.html) then the extension fails immediately because it sends the unescaped line directly to the terminal. The solutions seems pretty obvious, surround the "activeFile" line in the script with double-quotes and add a test to verify it will work with a test folder string that has a space in it. I just wanted to submit the issue before fixing, in case there was some reason this shouldn't be done, or if I had missed something. I'm not a regular vscode dev, I just happened to have this problem and know what the solution is.

https://github.com/bilelmsekni/componizer/blob/4b493db8098075ed8d5e18805fd8dc9f3ac0ec9c/extension/src/utils.ts#L28

**Comment by bilelmsekni** [comment]
Thanks for your feedback and the PR, I merged your fix and it will be shipped in 0.0.5 (will mention your name to thank you for the contribution )
