### ISSUE TITLE
feat: do not depend on global ng

### ISSUE THREAD

**Issue by chihab** [bilelmsekni/componizer#21]
## Feature description

Launch local ng command script rather than the global one.

## Implementation

Maybe by replacing 
```typescript
const script = `ng g @componizer/schematics:ng-componize ...`;
```

by 

```typescript
const script = `npx ng g @componizer/schematics:ng-componize ...`;
```
in `src/utils.ts`?

Not sure about the cwd though.

**UPDATE**
`npx` rather than `npm run` which depends on `"ng": "ng"` being present in `scripts`.

**Comment by bilelmsekni** [comment]
I'm not sure if I have tried this before but perhaps it deserves another chance.
I'll give it a try this weekend and see if it works

**Comment by chihab** [comment]
I can handle it @bilelmsekni and submit a PR.
Theoretically, there should be no issue since `npx` is now on the CLI requirements (given the required engine version)?

It looks that there is no real "e2e" test of the extension, the script is mocked so the update won't be tested out.

**Comment by bilelmsekni** [comment]
Yes please by all means, submit a PR :)

and also yes, the tests are mostly unit tests not E2E tests.
